- name: Configure proxy servers
  hosts: all
  become: true
  tasks:
  - name: Install chrony package
    package:
      name: chrony
      state: present
  - name: Update NTP server in chrony.conf
    lineinfile:
      path: /etc/chrony.conf
      state: present
      regexp: '^server'
      line: 'server 10.244.10.12 \nserver 10.244.10.13'
  - name: Restart chrony service
    service:
      name: chronyd
      state: restarted